# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
notARepository: skip
gui:
    nerdFontsVersion: "3"
    showBottomLine: false
    border: rounded
    mouseEvents: false
    windowSize: half
    theme:
        activeBorderColor:
            - cyan
        inactiveBorderColor:
            - magenta
git:
    parseEmoji: true
